export const SET_LOGIN_PENDING = 'login/SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'login/SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'login/SET_LOGIN_ERROR';
export const SET_AUTHENTICATION = 'login/SET_AUTHENTICATION';
